version: "3.9"

networks:
  myapp:
    driver: bridge

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myapp

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - myapp

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000"
    depends_on:
      - backend
    networks:
      - myapp

volumes:
  postgres-data:
    driver: local
