// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Luis Enrique Ramírez López",
            "url": "http://www.swagger.io/support",
            "email": "luian.ramirez.12@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sell": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sell a bound",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sell"
                ],
                "summary": "Sell a bound",
                "parameters": [
                    {
                        "description": "Sell Request",
                        "name": "sellRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SellRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SellResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response400WithResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response404WithResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response500WithResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.SellRequest": {
            "type": "object",
            "required": [
                "name",
                "price",
                "quantity"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 3,
                    "example": "name"
                },
                "price": {
                    "type": "number",
                    "maximum": 100000000,
                    "minimum": 0.0001,
                    "example": 1
                },
                "quantity": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 1
                }
            }
        },
        "domain.SellResponse": {
            "type": "object",
            "properties": {
                "folio": {
                    "type": "string",
                    "format": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "mensaje": {
                    "type": "string",
                    "format": "string",
                    "example": "Operación realizada con éxito"
                }
            }
        },
        "models.Response400WithResult": {
            "type": "object",
            "properties": {
                "detalles": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "string"
                    },
                    "example": [
                        "Error en la petición"
                    ]
                },
                "folio": {
                    "type": "string",
                    "format": "string",
                    "example": ""
                },
                "mensaje": {
                    "type": "string",
                    "format": "string",
                    "example": "Operación realizada sin éxito"
                }
            }
        },
        "models.Response404WithResult": {
            "type": "object",
            "properties": {
                "detalles": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "string"
                    },
                    "example": [
                        "No se encontró el recurso solicitado"
                    ]
                },
                "folio": {
                    "type": "string",
                    "format": "string",
                    "example": ""
                },
                "mensaje": {
                    "type": "string",
                    "format": "string",
                    "example": "Operación realizada con éxito"
                }
            }
        },
        "models.Response500WithResult": {
            "type": "object",
            "properties": {
                "detalles": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "string"
                    },
                    "example": [
                        "Error interno del servidor"
                    ]
                },
                "folio": {
                    "type": "string",
                    "format": "string",
                    "example": ""
                },
                "mensaje": {
                    "type": "string",
                    "format": "string",
                    "example": "Operación fallida"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Technical Challenge API",
	Description:      "REST API for the Technical Challenge",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
